name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Check version validity
        run: |
          export EXTENSION_ID=$(jq -r '.publisher' package.json).$(jq -r '.name' package.json)
          export PACKAGE_VERSION=$(jq -r '.version' package.json)
          export MARKETPLACE_VERSION=$(npx @vscode/vsce show $EXTENSION_ID --json | jq -j '.versions[0].version')
          dpkg --compare-versions $PACKAGE_VERSION "gt" $MARKETPLACE_VERSION
      - name: Publish extension
        run: npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
